### ISSUE TITLE
dbc.execute('VACUUM') error

### ISSUE THREAD

**Issue by SanaRinomi** [FlaminSarge/tf2idb#14]
I get the following error:
`Traceback (most recent call last):
  File "C:\Users\amelia\Desktop\tf2idb.py", line 228, in <module>
    main()
  File "C:\Users\amelia\Desktop\tf2idb.py", line 224, in main
    dbc.execute('VACUUM')
sqlite3.OperationalError: cannot VACUUM from within a transaction`

**Comment by fakuivan** [comment]
What version of python are you using? (``python -V``)

**Comment by Zolika1351** [comment]
Same here using Python 3.6.1, also accidentally tried to use 2.7.10 because I have both installed and got the same error.

**Comment by James76931** [comment]
Can confirm. Getting this issue on my end also.

**Comment by FlaminSarge** [comment]
That is really odd; I get no trouble on 3.5.3 and 2.7.10 with the VACUUM operation.

**Comment by FlaminSarge** [comment]
Also https://bugs.python.org/issue28518

**Comment by FlaminSarge** [comment]
(Simple fix would be to move the db.commit() line above the VACUUM line, probably. Might need to add another commit line, I'm not sure).
