### ISSUE TITLE
TF2idb error

### ISSUE THREAD

**Issue by Blackglade** [FlaminSarge/tf2idb#15]
I keep getting this error for some reason everytime I try to load the plugin on my test server.

```
L 05/10/2017 - 04:27:26: SourceMod error session started
L 05/10/2017 - 04:27:26: Info (map "ctf_2fort") (file "errors_20170510.log")
L 05/10/2017 - 04:27:26: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 05/10/2017 - 04:27:26: [SM] Blaming: tf2idb.smx
L 05/10/2017 - 04:27:26: [SM] Call stack trace:
L 05/10/2017 - 04:27:26: [SM]   [0] SQL_Query
L 05/10/2017 - 04:27:26: [SM]   [1] Line 381, tf2idb.sp::Native_FindItemCustom
L 05/10/2017 - 04:27:26: [SM]   [3] TF2IDB_FindItemCustom
L 05/10/2017 - 04:27:26: [SM]   [4] Line 72, C:\Users\Quantum\Desktop\PrivateFiles\TF2 Custom Plugins\include\tf2_taunts_tf2idb/taunt_cache_system.inc::CTauntCacheSystem.FromTF2IDB
L 05/10/2017 - 04:27:26: [SM]   [5] Line 30, tf2_taunts_tf2idb.sp::OnPluginStart
L 05/10/2017 - 04:27:26: [SM] Unable to load plugin "tf2_taunts_tf2idb.smx": Error detected in plugin startup (see error logs)

```

Here are the values @fakuivan asked for!
```
 sm_rcon sm plugins info tf2idb
  Filename: tf2idb.smx
  Title: TF2IDB (Item Schema Database)
  Author: Bottiger
  Version: 0.93
  URL: http://skial.com
  Status: running
  Timestamp: 03/01/2016 12:23:56
  Hash: e034fe0067278ca6f9628527824dca1e

 sm_rcon sm plugins info tf2_taunts_tf2idb
  Filename: tf2_taunts_tf2idb.smx
  Title: TF2 Taunts TF2IDB (An extensible taunt menu that updates along with tf2idb)
  Author: fakuivan
  Version: 1
  URL: https://forums.alliedmods.net/member.php?u=264797
  Error: Error detected in plugin startup (see error logs)
```

**Comment by Blackglade** [comment]
Just realized the version number for tf2idb was off... that's because I'm using a slightly modified version.. but rest assured when I put the original plugin as is on the server, I still get the same issue!

```
L 05/10/2017 - 04:38:36: SourceMod error session started
L 05/10/2017 - 04:38:36: Info (map "ctf_2fort") (file "errors_20170510.log")
L 05/10/2017 - 04:38:36: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 05/10/2017 - 04:38:36: [SM] Blaming: tf2idb.smx
L 05/10/2017 - 04:38:36: [SM] Call stack trace:
L 05/10/2017 - 04:38:36: [SM]   [0] SQL_Query
L 05/10/2017 - 04:38:36: [SM]   [1] Line 381, tf2idb.sp::Native_FindItemCustom
L 05/10/2017 - 04:38:36: [SM]   [3] TF2IDB_FindItemCustom
L 05/10/2017 - 04:38:36: [SM]   [4] Line 72, /home/travis/build/fakuivan/TF2-Taunts-TF2IDB/addons/sourcemod/scripting/include/tf2_taunts_tf2idb/taunt_cache_system.inc::CTauntCacheSystem.FromTF2IDB
L 05/10/2017 - 04:38:36: [SM]   [5] Line 53, /home/travis/build/fakuivan/TF2-Taunts-TF2IDB/addons/sourcemod/scripting/tf2_taunts_tf2idb.sp::OnPluginStart
L 05/10/2017 - 04:38:36: [SM] Unable to load plugin "tf2_taunts_tf2idb.smx": Error detected in plugin startup (see error logs)
```


```
 sm_rcon sm plugins info tf2_taunts_tf2idb
  Filename: tf2_taunts_tf2idb.smx
  Title: TF2 Taunts TF2IDB (An extensible taunt menu that updates along with tf2idb)
  Author: fakuivan
  Version: 1.5.1.47-tf2idb
  URL: https://forums.alliedmods.net/member.php?u=264797
  Error: Error detected in plugin startup (see error logs)

```

**Comment by fakuivan** [comment]
Add the source for tf2idb and the database so we can debug it. 

If you want something added to the taunts plugin, I suggest you open an issue on its GitHub page describing your request.

**Comment by Blackglade** [comment]
The modificiations was purely internal so I can integrate it with my server plugin.

What do you mean by add the source for tf2idb and the database? It's the most recently released one, no changes made.

**Comment by fakuivan** [comment]
At some point [``SQL_Query``](https://github.com/FlaminSarge/tf2idb/blob/master/scripting/tf2idb.sp#L484) recieved ``0`` (``INVALID_HANDLE``) as a database handle, and that should be imposible given that the only place where ``g_db`` is set is ``OnPluginStart`` and proper checks are implemented to bail out if ``SQLite_UseDatabase`` fails to connect (returns ``INVALID_HANDLE``). Furthermore, ``g_db`` is referenced when preparing the cache so it should fail there too. 

I don't think your source files are the same as in 0.93.

**Comment by Blackglade** [comment]
Okay so just to be completely sure I fully wiped the server, did a fresh install of sourcemod and metamod and then followed the instructions to install your plugin. Still getting the same issue.

 I've added the source for tf2idb and the database I'm using anyway...

Here is the raw for tf2idb plugin: https://pastebin.com/raw/L0umGfZU

and the database is the sample-db-2015-12-18.zip downloaded from this page: https://forums.alliedmods.net/showthread.php?t=255885

**Comment by Blackglade** [comment]
So I just read this line.... "You can use the pre-made database here but it is not recommended because I will not be updating it. You should follow the additional instructions below so you can make the database yourself after each update."

and so I tried to make my own database following the instructions and I keep getting this issue: https://puu.sh/vPgjn/d59ed7b25a.png

**Comment by fakuivan** [comment]
That script is for python 2, works fine on 2.7 . You can download that version of python or use [my python 3 port with a few enhancements](https://forums.alliedmods.net/showthread.php?p=2373435#post2373435).

**Comment by fakuivan** [comment]
Try reloading the taunt plugin (only the taunt plugin) with tf2idb loaded. It seems like the natives exposed before initialization.

**Comment by asherkin** [comment]
The bug here is in tf2_taunts_tf2idb, it is calling into tf2idb before OnAllPluginsLoaded.

**Comment by fakuivan** [comment]
I suspected that :P. Thanks Asher, I'll push an update ASAP.

**Comment by Blackglade** [comment]
So, should I just wait for an updating before trying it again?

**Comment by fakuivan** [comment]
We'll follow it up [here](https://github.com/fakuivan/TF2-Taunts-TF2IDB/issues/14). You can close this @FlaminSarge
