### ISSUE TITLE
Error on tf2idp load

### ISSUE THREAD

**Issue by Cave-Johnson10** [FlaminSarge/tf2idb#17]
L 07/31/2017 - 01:31:53: [SM] Exception reported: no such table: tf2idb_item
L 07/31/2017 - 01:31:53: [SM] Blaming: tf2idb.smx
L 07/31/2017 - 01:31:53: [SM] Call stack trace:
L 07/31/2017 - 01:31:54: [SM]   [0] SetFailState
L 07/31/2017 - 01:31:54: [SM]   [1] Line 104, tf2idb.sp::OnPluginStart
L 07/31/2017 - 01:31:54: [SM] Unable to load plugin "tf2idb.smx": Error detected in plugin startup (see error logs)

**Comment by FlaminSarge** [comment]
Seems like an outdated database file. Did you manage to run the latest python script to generate the DB?

**Comment by Cave-Johnson10** [comment]
yes I did

**Comment by FlaminSarge** [comment]
I just updated the python script to not break as per #14 on python 3.6 so try it again if it wasn't working before

**Comment by Cave-Johnson10** [comment]
alright redownloaded it and no error thanks.

**Comment by Rapti** [comment]
3½ years later I'm getting this error again.

`sm plugins load tf2idb
L 12/27/2020 - 15:28:09: [SM] Exception reported: no such table: tf2idb_item
L 12/27/2020 - 15:28:09: [SM] Blaming: tf2idb.smx
L 12/27/2020 - 15:28:09: [SM] Call stack trace:
L 12/27/2020 - 15:28:09: [SM]   [0] SetFailState
L 12/27/2020 - 15:28:09: [SM]   [1] Line 66, tf2idb.sp::OnPluginStart
[SM] Plugin tf2idb.smx failed to load: Error detected in plugin startup (see error logs).`

Only the line number seems to be different. Any ideas?

**Comment by japa4551** [comment]
Was having the same problem, and after half an hour after reading your comment i noticed the error XD
Thanks for pointing this out Rapti
