### ISSUE TITLE
Plugin tf2idb.smx failed to load: Native "TF2IDB_CustomQuery" was not found.

### ISSUE THREAD

**Issue by QuantumToasted** [FlaminSarge/tf2idb#18]
```
[SM] Plugin optional/tf2idb.smx failed to load: Native "TF2IDB_CustomQuery" was not found.
```
This happens when I attempt to load the plugin on my server. I created the new database today as well, and am using the newest release from GitHub. I feel like I'm just missing something important, but..

**Comment by FlaminSarge** [comment]
See if you can paste more lines of that log.

**Comment by QuantumToasted** [comment]
I feel like a dunce, but I cannot seem to find anything related to it in neither the server or Sourcemod logs. Not even the above message.

**Comment by FlaminSarge** [comment]
Closing until it's seen again

**Comment by SoulBlast35** [comment]
@FlaminSarge Im getting the same issue.

**Comment by FlaminSarge** [comment]
Do you have any logs? Server details?

**Comment by SoulBlast35** [comment]
One quick question, is the version on GitHub newer than the one on AlliedMods?

**Comment by fakuivan** [comment]
@SoulBlast35 you could say that. This is a fork more than a "newer version", given that the original author is not the one that contributes or controls this repo.

**Comment by SoulBlast35** [comment]
It's just the version on GitHub throws that error above and refuses to load.
