### ISSUE TITLE
SyntaxError: unexpected character after line continuation character

### ISSUE THREAD

**Issue by JaredKnushfur** [FlaminSarge/tf2idb#31]
No matter how I try, it  always gives me this error when I try to manually drag it into python. If I just double click, it opens then immediately closes python. Any insight on what went wrong? When I manually added my tf2 server path, I did replace \ with /, but that didn't seem to make a difference.

**Comment by JaredKnushfur** [comment]
Also, after loading in to it via IDE, I get
"Traceback (most recent call last):
  File "C:\Users\justa\Desktop\tf2idb\tf2idb.py", line 129, in <module>
    dbc.execute('INSERT INTO new_tf2idb_capabilities (id,capability) VALUES (?,?)', (id, name))
NameError: name 'name' is not defined
0
Traceback (most recent call last):
  File "C:\Users\justa\Desktop\tf2idb\tf2idb.py", line 129, in <module>
    dbc.execute('INSERT INTO new_tf2idb_capabilities (id,capability) VALUES (?,?)', (id, name))
NameError: name 'name' is not defined"
any info on how to define the name?

**Comment by FlaminSarge** [comment]
This could be a python2 vs python3 thing.

An aside, try https://github.com/nosoop/SM-TFEconDataCompat as it was just updated, I believe. It basically uses TF2-EconData and then pretends that it's TF2IDB when anything tries to use TF2IDB.

**Comment by JaredKnushfur** [comment]
It might work, but it seems to make it so the plugin I need TF2IDB for not work properly. I'm trying to use  this one: https://forums.alliedmods.net/showthread.php?t=293722
and with the fake TF2ECON, it doesn't seem to work. TF2 says it loads, but none of the commands are listed. I know it's not your plugin, but I think that TF2 taunt plugin will only work with the original TF2IDB

**Comment by JaredKnushfur** [comment]
also trying to boot it up using python 2.7 (which is the earliest version from 2015) gives a whole different error 
 "File "<stdin>", line 1
    C:\Users\INSERTNAMEHERE\Desktop\tf2idb\tf2idb.py
     ^"

**Comment by JaredKnushfur** [comment]
Nevermind? It works now! I just had to edit the .py script and boot into it via python 2.7!
