### ISSUE TITLE
backslash error

### ISSUE THREAD

**Issue by JaredKnushfurReal** [FlaminSarge/tf2idb#34]
So by default it uses "/" instead of "\" which causes it to fail due to a missing path. But when changing "/" to "\" like it should, running the module still generates a missing path because it doubles "\" so instead of "D:\steamgames" it becomes "D:\ \steamgames".

**Comment by JaredKnushfurReal** [comment]
"OSError: [Errno 22] Invalid argument: 'D:\ \steamgames\ \steamapps\ \common\team fortress 2\tfscripts\ \items\ \items_game.txt'"
(space put between the slashes so github actually displays 2)
Here's how it looks in the module itself: 
"TF_FOLDER = 'D:\steamgames\steamapps\common\team fortress 2\tf'
ITEMS_GAME = TF_FOLDER + 'scripts\items\items_game.txt'
DB_FILE = TF_FOLDER + 'addons\sourcemod\data\sqlite\tf2idb.sq3'"

**Comment by JaredKnushfurReal** [comment]
after messing with pathing, the double backslash issue still occurs. It was closed temporarily due to my own mistakes. However, this is what it outputs: "with open(ITEMS_GAME) as f:
IOError: [Errno 2] No such file or directory: 'D:\ \steamgames\ \steamapps\ \common\ \team fortress 2\ \tfscripts\ \items\ \items_game.txt'"
(backslashes are spaced out to allow github to show them)
When this is what is written in the module itself: "TF_FOLDER = r'D:\steamgames\steamapps\common\team fortress 2\tf'
ITEMS_GAME = TF_FOLDER + 'scripts\items\items_game.txt'
DB_FILE = TF_FOLDER + '\addons\sourcemod\data\sqlite\tf2idb.sq3'"

**Comment by JaredKnushfurReal** [comment]
I've never recieved this error before while updating the plugin, and I've been using it for a while. I have tried running it in Python 3.10 and Python 2.7, the same error occurs either way.

**Comment by JaredKnushfurReal** [comment]
Note for anyone new to python getting this issue: use "/" not "\"

**Comment by FlaminSarge** [comment]
Do you still have a use case for TF2IDB that cannot be solved with https://github.com/nosoop/SM-TFEconDataCompat ? Would recommend using that, if possible.
