### ISSUE TITLE
Adapter's ReloadConfigs() is called before database is ready

### ISSUE THREAD

**Issue by nosoop** [FlaminSarge/tf2idb#4]
I was told to *do it*

```
[SM] Exception reported: Invalid database Handle 0 (error: 4)
[SM] Blaming: tf2idb.smx()
[SM] Call stack trace:
[SM]   [0] SQL_Query
[SM]   [1] Line 504, tf2idb.sp::Native_FindItemCustom()
[SM]   [3] TF2IDB_FindItemCustom
[SM]   [4] Line 2032, tf2idb_tf2ii_compat.sp::GetMaxItemID()
[SM]   [5] Line 1031, tf2idb_tf2ii_compat.sp::ReloadConfigs()
[SM]   [6] Line 247, tf2idb_tf2ii_compat.sp::OnPluginStart()
```
Looks like the ez fix would be to move `ReloadConfigs()` and the library check to an `OnAllPluginsLoaded()`, assuming no TF2II-dependent plugins relied on things being ready by `OnPluginStart()`.

**Comment by FlaminSarge** [comment]
Should be fixed by https://github.com/FlaminSarge/tf2idb/commit/8ec10235deded07ff858ef7c6d126d900d4c6525
