### ISSUE TITLE
Improve on TF2II adapter's handling of multi-slot items (?)

### ISSUE THREAD

**Issue by nosoop** [FlaminSarge/tf2idb#5]
When passing in the class for `TF2II_GetItemSlot`, it should probably return the slot of the item when used by that class (and fall back to the generic if `TFClass_Unknown`).

Affects shotgun reskins (defined as mainly primary but equipped as secondary for Soldier, Pyro, Heavy) and B.A.S.E. Jumper, mainly.

Might need special handling for Randomizer; not sure how they deal with weapon slots.

[Wrote up a short test for the natives.](https://gist.github.com/nosoop/b81d32c04a3c75292b7e7f56ab411381)  Load and run `sm_tf2ii_test`.

**Comment by FlaminSarge** [comment]
Should be fixed by https://github.com/FlaminSarge/tf2idb/commit/8ec10235deded07ff858ef7c6d126d900d4c6525 though all that functionality should really be reworked.

**Comment by nosoop** [comment]
I'm not sure if it's fixed but I'll just assume it was so I can sweep up my open issues

¯\\\_(ツ)\_\/¯
