### ISSUE TITLE
Make adapter fail outright if TF2IDB is unloaded (?)

### ISSUE THREAD

**Issue by nosoop** [FlaminSarge/tf2idb#6]
With the schema originally being stored in memory, TF2II just wasn't intended to handle cases where the schema disappears.  Except for very early in plugin startup, the schema is always cached.

Might want to consider TF2IDB being unloaded a fail state for the adapter.

**Comment by FlaminSarge** [comment]
Fixed by b4a939c7b9a37d76cf8d9bdfef18512cf5715e1e? Maybe?

**Comment by nosoop** [comment]
Probably.  About a good a fix as we can have.
Fail state is reached and plugin gets unloaded as expected (and no error spam on latest stables), so I guess we're done here.

**Comment by FlaminSarge** [comment]
Wait, what about the multiple RegPluginLibrary calls? Or is that not an issue?

**Comment by nosoop** [comment]
Not an issue, I'd think &mdash; at that point, the plugin should be reloaded anyways, so it's outside of our scope.

Didn't realize paused plugins still listened to `OnLibrary*` forwards though, so I guess it wouldn't hurt to have a one-time-write flag set to true on first successful load and only do `RegPluginLibrary` that first time.

Libraries are weird.
